steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gen-lang-client-0625573011/rust-linux-mini-kernel:v7.0.0-beta', '-f', 'azure_build/Dockerfile.with-code', '.']
images:
- 'gcr.io/gen-lang-client-0625573011/rust-linux-mini-kernel:v7.0.0-beta'
